# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.CharField(max_length=512),
        ),
    ]
