# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"

  config.vm.network "forwarded_port", host: 8080, guest: 8080
  config.vm.network "forwarded_port", host: 8000, guest: 8000
  config.vm.network "forwarded_port", host: 8888, guest: 8888
  config.vm.network "forwarded_port", host: 1017, guest: 1017
  config.vm.network "forwarded_port", host: 6379, guest: 6379

  # config.vm.network "private_network", ip: "10.11.11.10"

  config.vm.synced_folder "D:/Projects/Python", "/projects"

  config.vm.provision :shell, :path => "provision.sh"
  
  config.ssh.username = 'ubuntu'
  config.ssh.password = 'ubuntu1235890'
end
