# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.network "forwarded_port", host: 8000, guest: 8000
  config.vm.network "forwarded_port", host: 8080, guest: 8080
  config.vm.network "forwarded_port", host: 8888, guest: 8888

  # config.vm.network "private_network", ip: "10.11.11.10"

  config.vm.synced_folder "..", "/project"

  config.vm.provision :shell, :path => "provision.sh"
  
  config.ssh.username = 'vagrant'
  config.ssh.password = 'vagrant'
end
